### ISSUE TITLE
effect id: skill_xp_multiplier not working for McMMO.

### ISSUE THREAD

**Issue by Gh9stt** [Auxilor/Boosters#5]
Can't seem to get the multiplier to work for McMMO.

Plugins: eco, ecoskills, boosters, mcmmo, protocollib, placeholderapi - all latest version.
Tested on latest version of paper and purpur 1.18.1.

I'm just using the config that comes with the plugin and it works with EcoSkills just not McMMO.
Can also use the skills arg to specify EcoSkills but not McMMO.

When loading up it says, [Boosters] Loaded integrations: mcMMO, PlaceholderAPI.

I tried seeing if it was because I have EcoSkills and it was just taking that over McMMO but if I take out EcoSkills I get an error and then can't use the effect id: skill_xp_multiplier (at least that's what I'm assuming the error below is)

[01:53:18 ERROR]: [Boosters] Plugin Boosters v3.0.0 has failed to register events for class com.willfp.boosters.libreforge.integrations.ecoskills.EffectSkillXpMultiplier because com/willfp/ecoskills/api/PlayerSkillExpGainEvent does not exist.

**Comment by WillFP** [comment]
Fix coming in next update
