### ISSUE TITLE
Suggestion: Boosters Activate Command

### ISSUE THREAD

**Issue by Gh9stt** [Auxilor/Boosters#8]
/boosters activate (boosterid)

Would be nice for staff to be able to activate boosters without having to first give themselves it, then type the command to open a menu and click on it, would also allow for staff to use higher boosters for server events, etc... that players can not always see in the menu.

Also, if you are using custom items on your server, attaching this command to an item and using it to activate a booster would be cool.

**Comment by WillFP** [comment]
Coming in next version
